name: Run BKAM Scraper

on:
  schedule:
    - cron: '30 13 * * *'  # Runs every day at 14:30 Morocco time (13:30 UTC)
  workflow_dispatch:  # Allows manual run from the GitHub interface

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: main.py
